apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres/deployment.yaml
  - api/deployment.yaml
  - api/migrate-job.yaml
  - web/deployment.yaml
  - ingress/ingress.yaml
